/*
 * CardinalOS Unified Commands Implementation
 * 300+ Linux + DOS commands with full compatibility
 */

void show_help(void) {
    printf("\033[96m");
    kernel_print("╔══════════════════════════════════════════════════════════════════╗\n");
    kernel_print("║        CARDINALOS UNIFIED COMMAND REFERENCE (300+ COMMANDS)      ║\n");
    kernel_print("╚══════════════════════════════════════════════════════════════════╝\n");
    printf("\033[0m\n");
    
    printf("\033[93m═══ LINUX FILE MANAGEMENT (ls, cd, pwd, mkdir, etc.) ═══\033[0m\n");
    kernel_print("  ls, dir              - List directory contents\n");
    kernel_print("  cd <dir>             - Change directory\n");
    kernel_print("  pwd                  - Print working directory\n");
    kernel_print("  mkdir <name>         - Create directory\n");
    kernel_print("  rmdir <name>         - Remove directory\n");
    kernel_print("  touch <file>         - Create empty file\n");
    kernel_print("  rm <file>            - Remove file\n");
    kernel_print("  cp <src> <dst>       - Copy file\n");
    kernel_print("  mv <src> <dst>       - Move/rename file\n");
    kernel_print("  cat <file>           - Display file contents\n");
    kernel_print("  more, less <file>    - Page through file\n");
    kernel_print("  head <file>          - Show first lines\n");
    kernel_print("  tail <file>          - Show last lines\n");
    kernel_print("  find <path>          - Find files\n");
    kernel_print("  locate <name>        - Locate files by name\n");
    kernel_print("  which <cmd>          - Show command path\n");
    kernel_print("  whereis <cmd>        - Locate binary/man pages\n");
    kernel_print("  file <name>          - Determine file type\n");
    kernel_print("  stat <file>          - Display file status\n");
    kernel_print("  ln <target> <link>   - Create symbolic link\n");
    kernel_print("  chmod <mode> <file>  - Change file permissions\n");
    kernel_print("  chown <user> <file>  - Change file owner\n");
    kernel_print("  chgrp <group> <file> - Change file group\n");
    kernel_print("  umask <mask>         - Set default permissions\n");
    kernel_print("  df                   - Disk space usage\n");
    kernel_print("  du <path>            - Directory space usage\n");
    kernel_print("  mount <dev> <mnt>    - Mount filesystem\n");
    kernel_print("  umount <path>        - Unmount filesystem\n");
    kernel_print("  fsck <device>        - Check filesystem\n");
    kernel_print("  fdisk <device>       - Partition disk\n");
    kernel_print("  mkfs <device>        - Create filesystem\n\n");
    
    printf("\033[93m═══ DOS FILE COMMANDS (COPY, DEL, TYPE, etc.) ═══\033[0m\n");
    kernel_print("  DIR [path]           - List directory (DOS)\n");
    kernel_print("  CD [path]            - Change directory (DOS)\n");
    kernel_print("  COPY <src> <dst>     - Copy file (DOS)\n");
    kernel_print("  DEL, ERASE <file>    - Delete file (DOS)\n");
    kernel_print("  TYPE <file>          - Display file (DOS)\n");
    kernel_print("  REN <old> <new>      - Rename file (DOS)\n");
    kernel_print("  MD, MKDIR <dir>      - Create directory (DOS)\n");
    kernel_print("  RD, RMDIR <dir>      - Remove directory (DOS)\n");
    kernel_print("  ATTRIB <file>        - Set file attributes\n");
    kernel_print("  XCOPY <src> <dst>    - Extended copy\n");
    kernel_print("  MOVE <src> <dst>     - Move file (DOS)\n");
    kernel_print("  TREE [path]          - Display directory tree\n");
    kernel_print("  COMP <f1> <f2>       - Compare files\n");
    kernel_print("  FC <file1> <file2>   - File compare\n");
    kernel_print("  DISKCOMP <d1> <d2>   - Compare disks\n");
    kernel_print("  DISKCOPY <s> <d>     - Copy disk\n");
    kernel_print("  FORMAT <drive>       - Format disk\n");
    kernel_print("  LABEL <drive>        - Set volume label\n");
    kernel_print("  VOL [drive]          - Show volume info\n");
    kernel_print("  CHKDSK [drive]       - Check disk\n");
    kernel_print("  SCANDISK [drive]     - Scan disk for errors\n\n");
    
    printf("\033[93m═══ LINUX PROCESS MANAGEMENT ═══\033[0m\n");
    kernel_print("  ps                   - List processes\n");
    kernel_print("  top, htop            - Task manager\n");
    kernel_print("  kill <pid>           - Kill process\n");
    kernel_print("  killall <name>       - Kill by name\n");
    kernel_print("  pkill <pattern>      - Kill by pattern\n");
    kernel_print("  bg                   - Background job\n");
    kernel_print("  fg                   - Foreground job\n");
    kernel_print("  jobs                 - List jobs\n");
    kernel_print("  nohup <cmd>          - Run immune to hangups\n");
    kernel_print("  nice <cmd>           - Run with priority\n");
    kernel_print("  renice <pri> <pid>   - Change priority\n");
    kernel_print("  pgrep <name>         - Find process by name\n");
    kernel_print("  pidof <name>         - Find PID\n");
    kernel_print("  pstree               - Process tree\n");
    kernel_print("  w, who, whoami       - Show logged users\n");
    kernel_print("  uptime               - System uptime\n");
    kernel_print("  free                 - Memory usage\n");
    kernel_print("  vmstat               - Virtual memory stats\n");
    kernel_print("  iostat               - I/O statistics\n\n");
    
    printf("\033[93m═══ LINUX NETWORK COMMANDS ═══\033[0m\n");
    kernel_print("  ifconfig, ip         - Network config\n");
    kernel_print("  ping <host>          - Ping host\n");
    kernel_print("  traceroute <host>    - Trace route\n");
    kernel_print("  netstat              - Network statistics\n");
    kernel_print("  ss                   - Socket statistics\n");
    kernel_print("  route                - Routing table\n");
    kernel_print("  arp                  - ARP cache\n");
    kernel_print("  hostname             - Show/set hostname\n");
    kernel_print("  nslookup <host>      - DNS lookup\n");
    kernel_print("  dig <domain>         - DNS query\n");
    kernel_print("  host <domain>        - DNS lookup\n");
    kernel_print("  wget <url>           - Download file\n");
    kernel_print("  curl <url>           - Transfer data\n");
    kernel_print("  ftp <host>           - FTP client\n");
    kernel_print("  ssh <user@host>      - SSH client\n");
    kernel_print("  scp <src> <dst>      - Secure copy\n");
    kernel_print("  rsync <src> <dst>    - Remote sync\n");
    kernel_print("  telnet <host>        - Telnet client\n");
    kernel_print("  nc, netcat           - Network utility\n");
    kernel_print("  tcpdump              - Packet capture\n");
    kernel_print("  wireshark            - Protocol analyzer\n");
    kernel_print("  nmap <target>        - Network scanner\n");
    kernel_print("  iptables             - Firewall config\n");
    kernel_print("  ufw                  - Uncomplicated firewall\n\n");
    
    printf("\033[93m═══ DOS NETWORK COMMANDS ═══\033[0m\n");
    kernel_print("  PING <host>          - Ping host (DOS)\n");
    kernel_print("  TRACERT <host>       - Trace route (DOS)\n");
    kernel_print("  PATHPING <host>      - Path analysis\n");
    kernel_print("  NETSTAT              - Network status (DOS)\n");
    kernel_print("  IPCONFIG             - IP configuration\n");
    kernel_print("  NSLOOKUP <host>      - DNS lookup (DOS)\n");
    kernel_print("  ARP                  - ARP table (DOS)\n");
    kernel_print("  ROUTE                - Route table (DOS)\n");
    kernel_print("  NET VIEW             - View network resources\n");
    kernel_print("  NET USE              - Map network drive\n");
    kernel_print("  NET SHARE            - Manage shares\n");
    kernel_print("  NET USER             - Manage users\n");
    kernel_print("  NET START            - Start service\n");
    kernel_print("  NET STOP             - Stop service\n");
    kernel_print("  FTP <host>           - FTP client (DOS)\n");
    kernel_print("  TELNET <host>        - Telnet (DOS)\n\n");
    
    printf("\033[93m═══ LINUX TEXT PROCESSING ═══\033[0m\n");
    kernel_print("  grep <pattern>       - Search text\n");
    kernel_print("  sed <script>         - Stream editor\n");
    kernel_print("  awk <prog>           - Text processing\n");
    kernel_print("  cut <file>           - Cut columns\n");
    kernel_print("  sort <file>          - Sort lines\n");
    kernel_print("  uniq <file>          - Remove duplicates\n");
    kernel_print("  wc <file>            - Count lines/words\n");
    kernel_print("  diff <f1> <f2>       - Compare files\n");
    kernel_print("  patch <file>         - Apply patch\n");
    kernel_print("  tr <set1> <set2>     - Translate characters\n");
    kernel_print("  tee <file>           - Split output\n");
    kernel_print("  xargs                - Build commands\n");
    kernel_print("  expand, unexpand     - Convert tabs\n");
    kernel_print("  join <f1> <f2>       - Join lines\n");
    kernel_print("  paste <f1> <f2>      - Merge lines\n");
    kernel_print("  column               - Format columns\n");
    kernel_print("  fmt                  - Format text\n");
    kernel_print("  pr                   - Format for printing\n");
    kernel_print("  fold                 - Wrap lines\n\n");
    
    printf("\033[93m═══ DOS BATCH COMMANDS ═══\033[0m\n");
    kernel_print("  ECHO <text>          - Display text\n");
    kernel_print("  REM <comment>        - Comment\n");
    kernel_print("  PAUSE                - Wait for key\n");
    kernel_print("  CLS                  - Clear screen\n");
    kernel_print("  EXIT                 - Exit shell\n");
    kernel_print("  SET <var>=<val>      - Set variable\n");
    kernel_print("  IF <cond>            - Conditional\n");
    kernel_print("  FOR <var> IN <set>   - Loop\n");
    kernel_print("  GOTO <label>         - Jump to label\n");
    kernel_print("  CALL <batch>         - Call batch file\n");
    kernel_print("  SHIFT                - Shift parameters\n");
    kernel_print("  CHOICE               - User choice\n");
    kernel_print("  PROMPT <text>        - Set prompt\n\n");
    
    printf("\033[93m═══ LINUX SYSTEM ADMINISTRATION ═══\033[0m\n");
    kernel_print("  sudo <cmd>           - Run as superuser\n");
    kernel_print("  su <user>            - Switch user\n");
    kernel_print("  useradd <user>       - Add user\n");
    kernel_print("  userdel <user>       - Delete user\n");
    kernel_print("  usermod <user>       - Modify user\n");
    kernel_print("  passwd <user>        - Change password\n");
    kernel_print("  groupadd <group>     - Add group\n");
    kernel_print("  groupdel <group>     - Delete group\n");
    kernel_print("  adduser <user>       - Interactive add user\n");
    kernel_print("  addgroup <group>     - Add group\n");
    kernel_print("  systemctl            - System control\n");
    kernel_print("  service <name>       - Service control\n");
    kernel_print("  init <level>         - Change runlevel\n");
    kernel_print("  shutdown             - Shutdown system\n");
    kernel_print("  reboot               - Reboot system\n");
    kernel_print("  halt                 - Halt system\n");
    kernel_print("  poweroff             - Power off\n");
    kernel_print("  dmesg                - Kernel messages\n");
    kernel_print("  journalctl           - System logs\n");
    kernel_print("  logger               - Add log entry\n");
    kernel_print("  cron, crontab        - Schedule tasks\n");
    kernel_print("  at <time>            - Schedule one-time job\n\n");
    
    printf("\033[93m═══ LINUX PACKAGE MANAGEMENT ═══\033[0m\n");
    kernel_print("  apt-get, apt         - Debian packages\n");
    kernel_print("  yum, dnf             - RedHat packages\n");
    kernel_print("  pacman               - Arch packages\n");
    kernel_print("  zypper               - OpenSUSE packages\n");
    kernel_print("  dpkg                 - Debian package tool\n");
    kernel_print("  rpm                  - RPM package tool\n");
    kernel_print("  snap                 - Snap packages\n");
    kernel_print("  flatpak              - Flatpak packages\n");
    kernel_print("  pip                  - Python packages\n");
    kernel_print("  npm                  - Node.js packages\n");
    kernel_print("  gem                  - Ruby packages\n");
    kernel_print("  cargo                - Rust packages\n\n");
    
    printf("\033[93m═══ LINUX ARCHIVE & COMPRESSION ═══\033[0m\n");
    kernel_print("  tar <opts> <file>    - Archive utility\n");
    kernel_print("  gzip <file>          - Compress with gzip\n");
    kernel_print("  gunzip <file>        - Decompress gzip\n");
    kernel_print("  bzip2 <file>         - Compress with bzip2\n");
    kernel_print("  bunzip2 <file>       - Decompress bzip2\n");
    kernel_print("  xz <file>            - Compress with xz\n");
    kernel_print("  unxz <file>          - Decompress xz\n");
    kernel_print("  zip <file>           - Create zip\n");
    kernel_print("  unzip <file>         - Extract zip\n");
    kernel_print("  rar <file>           - Create rar\n");
    kernel_print("  unrar <file>         - Extract rar\n");
    kernel_print("  7z <file>            - 7-Zip utility\n");
    kernel_print("  compress <file>      - Compress file\n");
    kernel_print("  uncompress <file>    - Uncompress file\n\n");
    
    printf("\033[93m═══ DOS SYSTEM COMMANDS ═══\033[0m\n");
    kernel_print("  VER                  - Display version\n");
    kernel_print("  TIME                 - Display/set time\n");
    kernel_print("  DATE                 - Display/set date\n");
    kernel_print("  MEM                  - Display memory\n");
    kernel_print("  DOSKEY               - Command history\n");
    kernel_print("  MODE                 - Configure devices\n");
    kernel_print("  HELP [command]       - Display help\n");
    kernel_print("  VER                  - OS version\n");
    kernel_print("  PATH                 - Display/set path\n");
    kernel_print("  SUBST                - Substitute drive\n");
    kernel_print("  ASSIGN               - Assign drive\n");
    kernel_print("  JOIN                 - Join drive to path\n");
    kernel_print("  PRINT                - Print file\n");
    kernel_print("  GRAPHICS             - Load graphics\n");
    kernel_print("  KEYB                 - Keyboard layout\n\n");
    
    printf("\033[93m═══ CARDINALOS EXPLOIT FRAMEWORK ═══\033[0m\n");
    kernel_print("  exploit-list         - List all 200+ exploits\n");
    kernel_print("  exploit-search <cve> - Search exploit database\n");
    kernel_print("  exploit-info <id>    - Show exploit details\n");
    kernel_print("  exploit-run <id>     - Execute exploit\n");
    kernel_print("  exploit-ms17010      - EternalBlue (SMB)\n");
    kernel_print("  exploit-ms08067      - Conficker worm vector\n");
    kernel_print("  exploit-log4shell    - Log4j RCE\n");
    kernel_print("  exploit-bluekeep     - RDP RCE (CVE-2019-0708)\n");
    kernel_print("  exploit-zerologon    - Netlogon elevation\n");
    kernel_print("  exploit-printnightmare - Print Spooler RCE\n");
    kernel_print("  exploit-proxylogon   - Exchange RCE chain\n");
    kernel_print("  exploit-shellshock   - Bash RCE\n");
    kernel_print("  exploit-heartbleed   - OpenSSL info leak\n");
    kernel_print("  exploit-dirty-cow    - Linux privilege escalation\n\n");
    
    printf("\033[93m═══ CARDINALOS C2 OPERATIONS ═══\033[0m\n");
    kernel_print("  c2-status            - Show C2 server status\n");
    kernel_print("  c2-start             - Start C2 listeners\n");
    kernel_print("  c2-stop              - Stop C2 server\n");
    kernel_print("  c2-sessions          - List active sessions\n");
    kernel_print("  c2-interact <id>     - Interact with session\n");
    kernel_print("  c2-beacon <id>       - Set beacon interval\n");
    kernel_print("  c2-kill <id>         - Kill session\n");
    kernel_print("  c2-migrate <pid>     - Process migration\n");
    kernel_print("  c2-inject <pid>      - Code injection\n");
    kernel_print("  c2-pivot <target>    - Pivot through session\n");
    kernel_print("  c2-exfil <file>      - Exfiltrate data\n");
    kernel_print("  c2-persist           - Install persistence\n");
    kernel_print("  c2-elevate           - Privilege escalation\n");
    kernel_print("  c2-lateral <target>  - Lateral movement\n");
    kernel_print("  c2-encrypt <algo>    - Set encryption\n");
    kernel_print("  c2-obfuscate         - Obfuscate traffic\n\n");
    
    printf("\033[93m═══ CARDINALOS PENETRATION TESTING ═══\033[0m\n");
    kernel_print("  nmap <target>        - Network port scanner\n");
    kernel_print("  portscan <ip>        - Fast port scanner\n");
    kernel_print("  vulnscan <target>    - Vulnerability scanner\n");
    kernel_print("  webscan <url>        - Web vulnerability scan\n");
    kernel_print("  sqlmap <url>         - SQL injection tool\n");
    kernel_print("  xsstrike <url>       - XSS detection\n");
    kernel_print("  dirb <url>           - Directory brute force\n");
    kernel_print("  nikto <url>          - Web server scanner\n");
    kernel_print("  wpscan <url>         - WordPress scanner\n");
    kernel_print("  enum4linux <ip>      - SMB enumeration\n");
    kernel_print("  smbclient <ip>       - SMB client\n");
    kernel_print("  rpcclient <ip>       - RPC client\n");
    kernel_print("  ldapsearch <host>    - LDAP enumeration\n");
    kernel_print("  snmpwalk <host>      - SNMP enumeration\n");
    kernel_print("  hydra <target>       - Password cracker\n");
    kernel_print("  john <hashfile>      - Password hash cracker\n");
    kernel_print("  hashcat <hash>       - Advanced hash cracker\n");
    kernel_print("  metasploit           - Launch Metasploit\n");
    kernel_print("  msfconsole           - MSF console\n");
    kernel_print("  msfvenom             - Payload generator\n");
    kernel_print("  beef                 - Browser Exploitation\n");
    kernel_print("  burpsuite            - Web proxy/scanner\n");
    kernel_print("  zaproxy              - OWASP ZAP proxy\n");
    kernel_print("  responder            - LLMNR/NBT-NS poisoner\n");
    kernel_print("  impacket             - Network protocol tools\n\n");
    
    printf("\033[93m═══ CARDINALOS STEALTH & EVASION ═══\033[0m\n");
    kernel_print("  stealth-on           - Enable stealth mode\n");
    kernel_print("  stealth-off          - Disable stealth mode\n");
    kernel_print("  hide-process <pid>   - Hide process from ps\n");
    kernel_print("  hide-file <path>     - Hide file from ls\n");
    kernel_print("  hide-network         - Hide network connections\n");
    kernel_print("  rootkit-install      - Install kernel rootkit\n");
    kernel_print("  rootkit-remove       - Remove rootkit\n");
    kernel_print("  anti-forensics       - Clear forensic traces\n");
    kernel_print("  log-wiper            - Wipe system logs\n");
    kernel_print("  timestamp-stomp      - Modify file timestamps\n");
    kernel_print("  av-bypass            - Bypass antivirus\n");
    kernel_print("  edr-bypass           - Bypass EDR\n");
    kernel_print("  sandbox-detect       - Detect sandbox\n");
    kernel_print("  vm-detect            - Detect virtual machine\n");
    kernel_print("  debugger-detect      - Detect debugger\n\n");
    
    printf("\033[93m═══ CARDINALOS POST-EXPLOITATION ═══\033[0m\n");
    kernel_print("  dump-creds           - Dump credentials\n");
    kernel_print("  mimikatz             - Windows credential dumper\n");
    kernel_print("  hashdump             - Dump password hashes\n");
    kernel_print("  sam-dump             - Dump SAM database\n");
    kernel_print("  lsass-dump           - Dump LSASS memory\n");
    kernel_print("  keylog-start         - Start keylogger\n");
    kernel_print("  keylog-stop          - Stop keylogger\n");
    kernel_print("  keylog-dump          - Dump keystrokes\n");
    kernel_print("  screenshot           - Capture screenshot\n");
    kernel_print("  webcam-capture       - Capture webcam\n");
    kernel_print("  audio-record         - Record audio\n");
    kernel_print("  clipboard-monitor    - Monitor clipboard\n");
    kernel_print("  browser-creds        - Extract browser passwords\n");
    kernel_print("  wifi-creds           - Extract WiFi passwords\n");
    kernel_print("  token-steal <pid>    - Steal access token\n");
    kernel_print("  getsystem            - Get SYSTEM privileges\n");
    kernel_print("  rev2self             - Revert to self\n\n");
    
    printf("\033[93m═══ GENERAL COMMANDS ═══\033[0m\n");
    kernel_print("  help                 - Show this help\n");
    kernel_print("  help dos             - DOS commands only\n");
    kernel_print("  help linux           - Linux commands only\n");
    kernel_print("  clear, cls           - Clear screen\n");
    kernel_print("  exit, quit           - Exit CardinalOS\n");
    kernel_print("  reboot               - Reboot system\n");
    kernel_print("  shutdown             - Shutdown system\n");
    kernel_print("  version, ver         - Show OS version\n");
    kernel_print("  uname                - System information\n");
    kernel_print("  info                 - System info\n\n");
}
